rpcEth: https://sepolia.infura.io/v3/
rpcOpt: https://optimism-sepolia.infura.io/v3/

parameters:
  - &rpcEthRemote "https://sepolia.infura.io/v3/"
  - &rpcOptRemote "https://optimism-sepolia.infura.io/v3/"
  - &rpcEthLocal "http://localhost:8545"
  - &rpcOptLocal "http://localhost:9545"
  - &agent "0x32A0E5828B62AAb932362a4816ae03b860b65e83"
  - &lido "0x3e3FE7dBc6B4C189E7128855dD526361c49b40Af"
  - &accountingOracle "0xd497Be005638efCf09F6BFC8DAFBBB0BB72cD991"
  - &wstETH "0xB82381A3fBD3FaFA77B3a7bE693342618240067b"
  - &stETH "0x3e3FE7dBc6B4C189E7128855dD526361c49b40Af"
  - &l1EmergencyBreaksMultisig "0xa5F1d7D49F581136Cf6e58B32cBE9a2039C48bA1"
  - &l2EmergencyBreaksMultisig "0xa5F1d7D49F581136Cf6e58B32cBE9a2039C48bA1"
  - &l1CrossDomainMessenger "0x58Cc85b8D04EA49cC6DBd3CbFFd00B4B8D6cb3ef"
  - &l2CrossDomainMessenger "0x4200000000000000000000000000000000000007"
  - &l2GovernanceExecutor "0xf695357C66bA514150Da95b189acb37b46DDe602"

testingParameters:
  lido: *lido
  accountingOracle: *accountingOracle
  tokenRateNotifier: "0x10cA9008D7dcea1Bed4d5394F8c58F3113A2814D"
  #opStackTokenRatePusher: ""
  l1NonRebasableToken: *wstETH
  l1RebasableToken: *stETH
  l1TokensHolder: "0xCDE580933C37Ed0d77c999454ab8728f3dCF2854"
  l2GovernanceExecutor: *l2GovernanceExecutor

statemate:
  rpcEthLocal: *rpcEthLocal
  rpcEthRemote: *rpcEthRemote
  rpcOptLocal: *rpcOptLocal
  rpcOptRemote: *rpcOptRemote

diffyscan:
  etherscanExplorerToken: ""
  optiscanExplorerToken: ""
  remoteRpcUrl: "https://sepolia.infura.io/v3/"
  localRpcUrl: "http://localhost:8545"
  githubApiToken: ""

deployParameters:
  rpcEth: *rpcEthRemote
  rpcOpt: *rpcOptRemote
  network: sepolia
  forking: true
  ethereum:
    tokenRateNotifier:
      lido: *lido
      tokenRateNotifierOwner: *agent
    opStackTokenRatePusher:
      messenger: *l1CrossDomainMessenger
      wstETH: *wstETH
      accountingOracle: *accountingOracle
      l2GasLimitForPushingTokenRate: 300000
    tokenBridge:
      proxyAdmin: *agent
      bridgeAdmin: *agent
      messenger: *l1CrossDomainMessenger
      accountingOracle: *accountingOracle
      l1NonRebasableToken: *wstETH
      l1RebasableToken: *stETH
      depositsEnabled: true
      withdrawalsEnabled: true
      depositsEnablers: [*agent]
      depositsDisablers: [*agent, *l1EmergencyBreaksMultisig]
      withdrawalsEnablers: [*agent]
      withdrawalsDisablers: [*agent, *l1EmergencyBreaksMultisig]
  optimism:
    tokenRateOracle:
      proxyAdmin: *l2GovernanceExecutor
      oracleAdmin: *l2GovernanceExecutor
      l2Messenger: *l2CrossDomainMessenger
      tokenRateOutdatedDelay: 86400
      maxAllowedL2ToL1ClockLag: 86400
      maxAllowedTokenRateDeviationPerDayBp: 500
      oldestRateAllowedInPauseTimeSpan: 86400
      minTimeBetweenTokenRateUpdates: 3600
      updateEnabled: true
      updateEnablers: [*l2GovernanceExecutor]
      updateDisablers: [*l2GovernanceExecutor, *l2EmergencyBreaksMultisig]
      initialTokenRateValue: 1000000000000000000000000000
      initialTokenRateL1Timestamp: 1719765972
    nonRebasableToken:
      proxyAdmin: *l2GovernanceExecutor
      signingDomainVersion: 1
    rebasableToken:
      proxyAdmin: *l2GovernanceExecutor
      signingDomainVersion: 1
    tokenBridge:
      messenger: *l2CrossDomainMessenger
      proxyAdmin: *l2GovernanceExecutor
      bridgeAdmin: *l2GovernanceExecutor
      depositsEnabled: true
      withdrawalsEnabled: true
      depositsEnablers: [*l2GovernanceExecutor]
      depositsDisablers: [*l2GovernanceExecutor, *l2EmergencyBreaksMultisig]
      withdrawalsEnablers: [*l2GovernanceExecutor]
      withdrawalsDisablers: [*l2GovernanceExecutor, *l2EmergencyBreaksMultisig]






