parameters:
  - &agent "0x32A0E5828B62AAb932362a4816ae03b860b65e83"
  - &lido "0x3e3FE7dBc6B4C189E7128855dD526361c49b40Af"
  - &accountingOracle "0xd497Be005638efCf09F6BFC8DAFBBB0BB72cD991"
  - &wstETH "0xB82381A3fBD3FaFA77B3a7bE693342618240067b"
  - &stETH "0x3e3FE7dBc6B4C189E7128855dD526361c49b40Af"
  - &l1EmergencyBreaksMultisig "0xa5F1d7D49F581136Cf6e58B32cBE9a2039C48bA1"
  - &l2EmergencyBreaksMultisig "0xa5F1d7D49F581136Cf6e58B32cBE9a2039C48bA1"
  - &l1CrossDomainMessenger "0x448A37330A60494E666F6DD60aD48d930AEbA381"
  - &l2CrossDomainMessenger "0x4200000000000000000000000000000000000007"

statemate:
  l1CrossDomainMessenger: *l1CrossDomainMessenger

deployParameters:
  forking: true
  ethereum:
    proxyAdmin: *agent
    opStackTokenRatePusher:
      messenger: *l1CrossDomainMessenger
      wstETH: *wstETH
      accountingOracle: *accountingOracle
      l2GasLimitForPushingTokenRate: 300000
    tokenBridge:
      bridgeAdmin: *agent
      messenger: *l1CrossDomainMessenger
      accountingOracle: *accountingOracle
      l1NonRebasableToken: *wstETH
      l1RebasableToken: *stETH
      depositsEnabled: true
      withdrawalsEnabled: true
      depositsEnablers: [*agent]
      depositsDisablers: [*agent, *l1EmergencyBreaksMultisig]
      withdrawalsEnablers: [*agent]
      withdrawalsDisablers: [*agent, *l1EmergencyBreaksMultisig]
  optimism:
    govBridgeExecutor:
      ovmL2Messenger: "0x4200000000000000000000000000000000000007"
      ethereumGovExecutor: *agent
      delay: 0
      gracePeriod: 86400
      minDelay: 0
      maxDelay: 1
      ovmGuiardian: "0x0000000000000000000000000000000000000000"
    tokenRateOracle:
      l2Messenger: *l2CrossDomainMessenger
      tokenRateOutdatedDelay: 93600  # 26 hours
      maxAllowedL2ToL1ClockLag: 86400
      maxAllowedTokenRateDeviationPerDayBp: 500
      oldestRateAllowedInPauseTimeSpan: 86400
      minTimeBetweenTokenRateUpdates: 3600
      updateEnabled: true
      updateEnablers: []
      updateDisablers: [*l2EmergencyBreaksMultisig]
      initialTokenRateValue: 1000000000000000000000000000
      initialTokenRateL1Timestamp: 1719765972
    nonRebasableToken:
      name: "Wrapped liquid staked Ether 2.0"
      symbol: "wstETH"
      signingDomainVersion: 1
    rebasableToken:
      name: "Liquid staked Ether 2.0"
      symbol: "stETH"
      signingDomainVersion: 1
    tokenBridge:
      messenger: *l2CrossDomainMessenger
      l1NonRebasableToken: *wstETH
      l1RebasableToken: *stETH
      depositsEnabled: true
      withdrawalsEnabled: true
      depositsEnablers: []
      depositsDisablers: [*l2EmergencyBreaksMultisig]
      withdrawalsEnablers: []
      withdrawalsDisablers: [*l2EmergencyBreaksMultisig]

testingParameters:
  lido: *lido
  accountingOracle: *accountingOracle
  tokenRateNotifier: "0x10cA9008D7dcea1Bed4d5394F8c58F3113A2814D"
  l1NonRebasableToken: *wstETH
  l1RebasableToken: *stETH
  l1TokensHolder: "0xCDE580933C37Ed0d77c999454ab8728f3dCF2854"
